import CoreImage.CIFilterBuiltins
import SwiftUI

/// Standalone QR generator used by Settings → Share Invite Key and the
/// per-identity invite hero. Mirrors the design's `QRCode` helper —
/// generated by Core Image, drawn pixel-aligned, with a centred Onym
/// mark badge punched into the middle.
struct SettingsQRCode: View {
    let value: String
    var size: CGFloat = 220

    var body: some View {
        ZStack {
            if let image = generate() {
                Image(uiImage: image)
                    .interpolation(.none)
                    .resizable()
                    .scaledToFit()
                    .frame(width: size, height: size)
            } else {
                RoundedRectangle(cornerRadius: 8)
                    .fill(OnymTokens.surface3)
                    .frame(width: size, height: size)
            }
            // Centred Onym mark badge
            RoundedRectangle(cornerRadius: size * 0.05, style: .continuous)
                .fill(OnymTokens.surface2)
                .frame(width: size * 0.22, height: size * 0.22)
                .overlay(OnymMark(size: size * 0.18, color: OnymTokens.text))
        }
        .background(OnymTokens.surface2)
        .clipShape(RoundedRectangle(cornerRadius: 12, style: .continuous))
    }

    private func generate() -> UIImage? {
        let filter = CIFilter.qrCodeGenerator()
        filter.message = Data(value.utf8)
        filter.correctionLevel = "M"
        guard let out = filter.outputImage else { return nil }
        let scale = size / out.extent.size.width
        let scaled = out.transformed(by: CGAffineTransform(scaleX: scale, y: scale))
        let ctx = CIContext()
        guard let cg = ctx.createCGImage(scaled, from: scaled.extent) else { return nil }
        return UIImage(cgImage: cg)
    }
}

/// Build the deeplink-style invite URL for an identity's BLS public
/// key. Mirrors the format the design uses — `https://onym.chat?payload=…`
/// with the truncated key as the payload prefix. Real production
/// invitee links live in the Group flow's `IntroCapability` — this is
/// the per-identity equivalent surfaced from Settings.
func settingsInviteURL(blsPublicKey: Data) -> String {
    let hex = blsPublicKey.prefix(22).map { String(format: "%02x", $0) }.joined()
    return "https://onym.chat?payload=\(hex)"
}
